# Generated by Django 4.0 on 2022-03-06 13:59

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('genericuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feedbacks.genericuser')),
                ('guid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(3, 'LEVEL 3'), (4, 'LEVEL 4'), (5, 'LEVEL 5'), (6, 'LEVEL 6')], default=3)),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Male'), (1, 'Female')], null=True)),
                ('is_scholarship', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('feedbacks.genericuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
