# Generated by Django 4.0 on 2022-03-23 11:19

from django.db import migrations
import feedbacks.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='genericuser',
            managers=[
                ('objects', feedbacks.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('objects', feedbacks.models.UserManager()),
            ],
        ),
    ]
