# Generated by Django 4.0 on 2022-03-06 14:17

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=250, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('genericuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feedbacks.genericuser')),
                ('guid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_leader', models.BooleanField(default=False)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teachers', to='feedbacks.module')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('feedbacks.genericuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('text', models.TextField()),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='feedbacks.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbacks.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='feedbacks.teacher')),
            ],
        ),
    ]
