# Generated by Django 4.0 on 2022-03-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_teacher_first_name_teacher_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='student',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
