version: '3.8'

services:
  feedbacks:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - .env.dev
  feedbacks-db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=feedbacks
      - POSTGRES_PASSWORD=feedbacks
      - POSTGRES_DB=feedbacks_dev

volumes:
  postgres_data:

